import { ProposalData } from "./types";

export const INITIAL_DATA: ProposalData = {
  client: { name: "Makayla", age: 0 },
  planName: "环宇盈活储蓄保险计划",
  premium: { total: 38500, paymentType: "5年" },
  legacy: { secondOwner: true, successorInsured: true },
  scenarioA: {
    year10: { surrender: 46519, death: 46519 }, 
    year20: { surrender: 1021317, death: 1329944 }, 
    year30: { surrender: 2606450, death: 2606450 },
    year40: { surrender: 5200000, death: 5200000 },
  },
  scenarioB: {
    annualWithdrawal: 35500,
    withdrawalStartYear: 6,
    year10: { cumulative: 177500, remaining: 549218 },
    year20: { cumulative: 532500, remaining: 682880 }, 
    year30: { cumulative: 887500, remaining: 862885 },
    year40: { cumulative: 1242500, remaining: 1197686 },
  },
  scenarioC: {
    goals: [
      { policyYearStart: 19, policyYearEnd: 22, amount: 95062, cumulative: 380248, remainingValue: 1099791, purpose: "大学教育基金 (University Education)", generation: "Gen 1", genLabel: "第一代: 创富" },
      { policyYearStart: 23, policyYearEnd: 23, amount: 124570, cumulative: 504818, remainingValue: 777940, purpose: "外国升学基金 (Overseas Studies)", generation: "Gen 1", genLabel: "第一代: 创富" },
      { policyYearStart: 30, policyYearEnd: 30, amount: 198252, cumulative: 703070, remainingValue: 1021397, purpose: "结婚/创业金 (Marriage/Startup)", generation: "Gen 1", genLabel: "第一代: 创富" },
      { policyYearStart: 65, policyYearEnd: 85, amount: 2461159, cumulative: 52387409, remainingValue: 4801944, purpose: "退休基金 (Retirement Fund)", generation: "Gen 1", genLabel: "第一代: 享受" },
      { policyYearStart: 80, policyYearEnd: 80, amount: 7621122, cumulative: 60008531, remainingValue: 9537610, purpose: "传承予子女 (Gift to Descendants)", generation: "Gen 2", genLabel: "第二代: 传承" },
      { policyYearStart: 90, policyYearEnd: 90, amount: 15995028, cumulative: 76003559, remainingValue: 20034946, purpose: "家族遗产 (Compassionate Legacy)", generation: "Gen 3", genLabel: "第三代: 永续" },
      { policyYearStart: 100, policyYearEnd: 100, amount: 32461656, cumulative: 108465215, remainingValue: 40676436, purpose: "百年基业 (Centennial Legacy)", generation: "Gen 3", genLabel: "第三代: 永续" },
    ]
  },
  promo: {
    lumpSum: { enabled: true, percent: 2 },
    fiveYear: { enabled: false, percent: 10 },
    prepay: { enabled: true, rate: 3.8, deadline: "2025-01-31" },
  },
};

// Map for translating default content data (like Plan Name and Goals) from Simplified to Traditional
export const HK_DATA_MAP: Record<string, string> = {
  "环宇盈活储蓄保险计划": "環宇盈活儲蓄保險計劃",
  "大学教育基金 (University Education)": "大學教育基金 (University Education)",
  "外国升学基金 (Overseas Studies)": "外國升學基金 (Overseas Studies)",
  "结婚/创业金 (Marriage/Startup)": "結婚/創業金 (Marriage/Startup)",
  "退休基金 (Retirement Fund)": "退休基金 (Retirement Fund)",
  "传承予子女 (Gift to Descendants)": "傳承予子女 (Gift to Descendants)",
  "家族遗产 (Compassionate Legacy)": "家族遺產 (Compassionate Legacy)",
  "百年基业 (Centennial Legacy)": "百年基業 (Centennial Legacy)"
};

export const TRANSLATIONS = {
  'zh-CN': {
    title: "私人财富管理建议书",
    clientName: "客户姓名",
    entryAge: "投保年龄",
    planName: "计划名称",
    totalPremium: "总保费",
    paymentType: "缴费方式",
    policyContinuation: "保单延续性: 设第二持有人选项",
    coreValues: "核心价值",
    wealthGrowth: "财富增值",
    wealthLegacy: "财富传承",
    flexibleLegacy: "灵活传承",
    currencyConfig: "货币配置",
    scenarioA: "情境 A: 资本积累",
    scenarioB: "情境 B: 被动收入",
    scenarioC: "情境 C: 人生目标规划",
    age: "年龄",
    ageUnit: "岁",
    policyYear: "保单年度",
    surrenderValue: "退保价值 (USD)",
    deathBenefit: "身故赔偿 (USD)",
    totalReturn: "总回报率 (%)",
    annualWithdrawal: "年提取",
    cumulativeWithdrawal: "累计提取 (USD)",
    remainingValue: "剩余价值 (USD)",
    generation: "世代",
    purpose: "用途说明",
    annualAmt: "年度提取 (USD)",
    promotions: "推广优惠",
    rebateLumpSum: "一笔过",
    rebate5Year: "5年缴",
    prepayInterest: "预缴利率优惠",
    disclaimerTitle: "免责声明:",
    disclaimerText: "本文件仅供参考，不构成任何要约或招揽。所有红利及分红均为非保证。投资涉及风险，阁下应留意美息走势对预缴利率的影响。",
    startYear: "第",
    endYear: "年起",
    year: "年",
    to: "至",
    rebate: "保费回赠",
    editData: "编辑数据",
    downloadPDF: "下载 / 打印 PDF",
    proposalPreview: "建议书预览 (2 页)",
    clientOverview: "客户概览",
    threeGenPath: "三代传承・富足路径",
    gen1: "第一代",
    gen1Desc: "创富与享受",
    gen1Short: "创富",
    gen2: "第二代",
    gen2Desc: "传承与扶持",
    gen2Short: "传承",
    gen3: "第三代",
    gen3Desc: "基业长青",
    newGoal: "新目标",
    policyLegacyFeatures: "保单传承功能",
    secondOwner: "第二持有人",
    successorInsured: "后备受保人",
  },
  'zh-HK': {
    title: "私人財富管理建議書",
    clientName: "客戶姓名",
    entryAge: "投保年齡",
    planName: "計劃名稱",
    totalPremium: "總保費",
    paymentType: "繳費方式",
    policyContinuation: "保單延續性: 設第二持有人選項",
    coreValues: "核心價值",
    wealthGrowth: "財富增值",
    wealthLegacy: "財富傳承",
    flexibleLegacy: "靈活傳承",
    currencyConfig: "貨幣配置",
    scenarioA: "情境 A: 資本積累",
    scenarioB: "情境 B: 被動收入",
    scenarioC: "情境 C: 人生目標規劃",
    age: "年齡",
    ageUnit: "歲",
    policyYear: "保單年度",
    surrenderValue: "退保價值 (USD)",
    deathBenefit: "身故賠償 (USD)",
    totalReturn: "總回報率 (%)",
    annualWithdrawal: "年提取",
    cumulativeWithdrawal: "累計提取 (USD)",
    remainingValue: "剩餘價值 (USD)",
    generation: "世代",
    purpose: "用途說明",
    annualAmt: "年度提取 (USD)",
    promotions: "推廣優惠",
    rebateLumpSum: "一筆過",
    rebate5Year: "5年繳",
    prepayInterest: "預繳利率優惠",
    disclaimerTitle: "免責聲明:",
    disclaimerText: "本文件僅供參考，不構成任何要約或招攬。所有紅利及分紅均為非保證。投資涉及風險，閣下應留意美息走勢對預繳利率的影響。",
    startYear: "第",
    endYear: "年起",
    year: "年",
    to: "至",
    rebate: "保費回贈",
    editData: "編輯數據",
    downloadPDF: "下載 / 列印 PDF",
    proposalPreview: "建議書預覽 (2 頁)",
    clientOverview: "客戶概覽",
    threeGenPath: "三代傳承・富足路徑",
    gen1: "第一代",
    gen1Desc: "創富與享受",
    gen1Short: "創富",
    gen2: "第二代",
    gen2Desc: "傳承與扶持",
    gen2Short: "傳承",
    gen3: "第三代",
    gen3Desc: "基業長青",
    newGoal: "新目標",
    policyLegacyFeatures: "保單傳承功能",
    secondOwner: "第二持有人",
    successorInsured: "後備受保人",
  }
};

export const SYSTEM_INSTRUCTION = ``;
