import { ImageResponse } from '@vercel/og';

export const config = {
    runtime: 'edge',
};

export default function handler(req: Request) {
    try {
        const { searchParams } = new URL(req.url);

        // Get dynamic text from query params
        // Example usage: /api/og?title=My%20Proposal&date=2023-10-25
        const title = searchParams.get('title') || 'Proposal Generator';
        const subtitle = searchParams.get('subtitle') || 'Generated by Vercel OG';

        return new ImageResponse(
            (
                <div
                    style={{
                        height: '100%',
                        width: '100%',
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'center',
                        justifyContent: 'center',
                        backgroundColor: 'white',
                        backgroundImage: 'radial-gradient(circle at 25px 25px, lightgray 2%, transparent 0%), radial-gradient(circle at 75px 75px, lightgray 2%, transparent 0%)',
                        backgroundSize: '100px 100px',
                    }}
                >
                    <div
                        style={{
                            display: 'flex',
                            flexDirection: 'column',
                            alignItems: 'center',
                            justifyContent: 'center',
                            backgroundColor: 'white',
                            border: '1px solid black',
                            borderRadius: '20px',
                            padding: '40px 80px',
                            boxShadow: '10px 10px 0px 0px rgba(0,0,0,1)',
                        }}
                    >
                        <div
                            style={{
                                fontSize: 60,
                                fontWeight: 900,
                                color: 'black',
                                marginBottom: 20,
                                textAlign: 'center',
                                fontFamily: 'sans-serif',
                            }}
                        >
                            {title}
                        </div>
                        <div
                            style={{
                                fontSize: 30,
                                color: '#666',
                                textAlign: 'center',
                                fontFamily: 'sans-serif',
                            }}
                        >
                            {subtitle}
                        </div>
                    </div>
                </div>
            ),
            {
                width: 1200,
                height: 630,
            },
        );
    } catch (e: any) {
        return new Response(`Failed to generate the image`, {
            status: 500,
        });
    }
}
